<?php

/**
 * @file
 * Hash Cash plugins for Panels.
 */

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function panels_hash_cache_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implementation of hook_menu().
 */
function panels_hash_cache_menu() {
  $items = array();
  $items['admin/settings/panels_hash_cache'] = array(
    'title' => 'Panels Hash Cache',
    'description' => 'Adjust Panels Hash Cache settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('panels_hash_cache_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function panels_hash_cache_admin_settings(){
  $form = array();
  $form['panels_hash_cache_reset_key'] = array(
	  '#type' => 'textfield',
		'#title' => 'Reset Key',
		'#default_value' => variable_get('panels_hash_cache_reset_key', ''),
		'#description' => t('Optionally allow us to regenerate the cache from the URL using a key by hitting the page with the query "?panels-hash-cache-reset={key}". This lets us, for example, to automatically re-generate a cache using cron hitting a url. This way users never see uncached content.'),
  );
	$form = system_settings_form($form);
  return $form;
}